### PR TITLE
Testing of the new release

### LINKED ISSUE #13: [META] Improve documentation
**Is your feature request related to a problem? Please describe.**

The current documentation is vague, hardly understandable by most people.

**Describe the solution you'd like**

Need to explain clearly everything

**Describe alternatives you've considered**

### LINKED ISSUE #16: [META] Aggressive testing for all functions/modules
Try to pass different kinds of input, especially for the new ```console_application.py```.

### LINKED ISSUE #20: [BUG] Issue with Linear Scale Graph
When using Linear scales, the graph lines of some countries do not appear on the plotted graph
## Expected Behavior
Graph lines of all countries should appear on the graph

## Current Behavior
Graph lines for some countries do not appear on the graph

## Possible Solution
Check linear scale code for possible errors

## Steps to Reproduce
1. Run console-application.py, World tally plot mode
2. Countries inputted (Singapore, Malaysia, Qatar, China, US) in order
3. Date inputted (04-05-2020)
4. Timespan (40 Days)
5. Plot scale **(linear)**
6. Plot type (cdra)

## Context (Environment)
The issue caused some of the graph lines of some countries to not appear, which affects the overall world tally graph.

## Detailed Description
Trying to plot graphs between countries that have a large number of COVID-19 cases and a low number of COVID-19 cases would cause some graph lines to not display correctly.

## Possible Implementation
N/A

image
[Image: **Singapore graph line not showing**]

image
[Image: **Singapore and Malaysia graph line not showing**]

image
[Image: **Singapore graph line not showing**]

image
[Image: **Singapore and Malaysia graph line not showing**]

### PR DESCRIPTION
**Pull request by aaronleaa**
5 May 2020
Updated **requirements.txt**

First Change
- Changed matplotlib module requirement from **3.03** to **3.20**

Second Change
- Changed matplotlib module requirement from **3.20** to **3.03 or ABOVE**

Reverted tally_visualiser back to **3.7.6** from **3.5.2**

### CODE REVIEW

**Comment by MunchDev** [comment]
This PR closes #13

**Comment by aaronleaa** [comment]
Updated README.md

- Fixed some spelling and grammar errors

**Comment by MunchDev** [comment]
Bug in Issue #20 reported, further retesting is required once fix is in @aaronleaa

**Comment by MunchDev** [comment]
Issue #20 is now closed, no modification will be made against this bug. No retesting is needed.

**Review by MunchDev — APPROVED** [review]

**Pull request merged**
